// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int n = Integer.parseInt(args[0]);
		int countAboveHalf = 0;
		int countBelowHalf = 0;
		for (int i = 0 ; i < n; i = i + 1) {
			if (Math.random() > 0.5) {
				countAboveHalf = countAboveHalf + 1;
			} else {
				countBelowHalf = countBelowHalf + 1;
			}
		}
		if (countBelowHalf == 0) {
			System.out.println("> 0.5: " + countAboveHalf + " times");
			System.out.println("<= 0.5: " + countBelowHalf + " times");
			
		} else {
		System.out.println("> 0.5: " + countAboveHalf + " times");
		System.out.println("<= 0.5: " + countBelowHalf + " times");
		System.out.println("Ratio: " + (double)countAboveHalf / countBelowHalf);
	   
	}
}
}